version: '3.6'

services:
  java_app:
    container_name: java_app
    image: jazael/bdncpractica:0.4
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db_personas

  db_personas:
    container_name: db_personas
    image: mongo:7.0.8
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mibase
  
  angular_app:
      depends_on:
        - java_app
      ports:
        - 4200:80
      container_name: angular_app
      image: jazael/frontbdnc:0.1